import subprocess
import sys
import json
import re
import time
from pathlib import Path


def get_base_dir():
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


BASE_DIR         = get_base_dir()
API_CONFIG_PATH  = BASE_DIR / "config" / "api_keys.json"
PROJECTS_DIR     = Path.home() / "Desktop" / "JarvisProjects"
MAX_FIX_ATTEMPTS = 5
MODEL_PLANNER    = "gemini-2.5-flash"
MODEL_WRITER     = "gemini-2.5-flash"
MODEL_DESIGN     = "gemini-2.5-flash"
STATIC_SITE_FILES = ("index.html", "styles.css", "script.js")
FULLSTACK_MARKERS = (
    "business", "бизнес", "company", "crm", "auth", "admin", "dashboard",
    "database", "backend", "api", "production", "saas", "startup", "магазин"
)

def _get_api_key() -> str:
    with open(API_CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)["gemini_api_key"]


def _get_model(model_name: str):
    import google.generativeai as genai
    genai.configure(api_key=_get_api_key())
    return genai.GenerativeModel(model_name)


def _strip_fences(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```[a-zA-Z]*\r?\n?", "", text)
    text = re.sub(r"\r?\n?```\s*$", "", text)
    return text.strip()


def _safe_project_name(name: str, fallback: str = "jarvis_project") -> str:
    cleaned = re.sub(r"[^\w\-]", "_", (name or fallback).strip().lower())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    return cleaned or fallback


def _looks_like_static_site(description: str, language: str, project_type: str = "") -> bool:
    text = f"{description} {language} {project_type}".lower()
    site_words = (
        "mini site", "мини сайт", "мини-сайт", "landing", "лендинг",
        "website", "web site", "сайт", "html", "frontend", "web app",
        "portfolio", "dashboard", "calculator", "калькулятор"
    )
    server_words = ("backend", "database", "api server", "django", "flask", "fastapi")
    return any(w in text for w in site_words) and not any(w in text for w in server_words)


def _looks_like_fullstack_site(description: str, language: str, project_type: str = "") -> bool:
    text = f"{description} {language} {project_type}".lower()
    return (
        project_type.lower() in ("fullstack", "production_website", "saas", "business_site")
        or ("сайт" in text and any(m in text for m in FULLSTACK_MARKERS))
        or ("website" in text and any(m in text for m in FULLSTACK_MARKERS))
    )


def _build_fullstack_website(description: str, project_name: str, speak=None, player=None) -> str:
    def log(msg: str):
        print(f"[DevAgent] {msg}")
        if player:
            player.write_log(f"[DevAgent] {msg}")

    proj_name = _safe_project_name(project_name, "jarvis_fullstack_site")
    project_dir = PROJECTS_DIR / proj_name
    frontend = project_dir / "frontend"
    backend = project_dir / "backend"
    for path in (frontend / "src", backend / "app"):
        path.mkdir(parents=True, exist_ok=True)

    log("Building production fullstack website scaffold...")
    brand = proj_name.replace("_", " ").title()
    (project_dir / "README.md").write_text(f"""# {brand}

Generated by JARVIS as a production-oriented fullstack website scaffold.

Request:
{description}

## Architecture
- Frontend: modern responsive React-style SPA structure (plain Vite-ready files)
- Backend: FastAPI-style API structure with auth boundaries and SQLite schema
- Database: `backend/schema.sql`
- Admin dashboard: `frontend/src/admin.js`
- SEO: `frontend/index.html` meta tags and semantic sections
- Docker: `Dockerfile` files and `docker-compose.yml`

## Next steps
1. Review `.env.example`.
2. Install frontend/backend dependencies.
3. Replace placeholder business copy and API keys.
4. Run tests and deploy.
""", encoding="utf-8")

    (project_dir / "docker-compose.yml").write_text("""services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    env_file: .env
    volumes: ["./backend/data:/app/data"]
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    depends_on: [backend]
""", encoding="utf-8")
    (project_dir / ".env.example").write_text("""APP_SECRET=change-me
DATABASE_URL=sqlite:///data/app.db
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=change-me
""", encoding="utf-8")

    (frontend / "package.json").write_text(json.dumps({
        "scripts": {"dev": "vite --host 0.0.0.0", "build": "vite build", "preview": "vite preview"},
        "dependencies": {"@vitejs/plugin-react": "latest", "vite": "latest", "react": "latest", "react-dom": "latest", "lucide-react": "latest"},
        "devDependencies": {}
    }, indent=2), encoding="utf-8")
    (frontend / "Dockerfile").write_text("""FROM node:22-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]
""", encoding="utf-8")
    premium_done = False
    try:
        log("Designing premium business front-end...")
        html = _generate_site_html(
            f"A premium production marketing + product website for: {description}. "
            f"Brand name: {brand}. Include hero, features, pricing, testimonials, FAQ and footer.",
            log=log,
        )
        (frontend / "index.html").write_text(html.strip() + "\n", encoding="utf-8")
        premium_done = True
        log("Premium front-end generated.")
    except Exception as e:
        log(f"Premium generation fell back to scaffold: {e}")

    if not premium_done:
        (frontend / "index.html").write_text(f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="{brand} - modern business platform generated by JARVIS" />
  <title>{brand}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.js"></script>
</body>
</html>
""", encoding="utf-8")
    (frontend / "src" / "main.js").write_text(f"""import './styles.css';
import {{ renderAdmin }} from './admin.js';

const app = document.querySelector('#root');
const brand = {brand!r};

app.innerHTML = `
  <main class="shell">
    <nav class="topbar">
      <strong>${{brand}}</strong>
      <div><a href="#features">Features</a><a href="#admin">Admin</a><a href="#contact">Contact</a></div>
    </nav>
    <section class="hero">
      <div>
        <p class="eyebrow">AI-built production scaffold</p>
        <h1>Modern digital operating system for your business</h1>
        <p class="lead">Responsive website, API-ready backend, auth boundaries, admin dashboard, SEO structure, and automation hooks.</p>
        <button id="demo">Request demo</button>
      </div>
      <aside class="panel"><h2>Live Metrics</h2><p>Leads: <b>128</b></p><p>Conversion: <b>14.8%</b></p><p>Status: <b>Operational</b></p></aside>
    </section>
    <section id="features" class="grid">
      <article><h3>Auth-ready</h3><p>Token boundaries and user schema prepared.</p></article>
      <article><h3>Admin dashboard</h3><p>Manage leads, customers, content and automations.</p></article>
      <article><h3>Automation hooks</h3><p>Connect Telegram, WhatsApp, CRM and scheduled tasks.</p></article>
    </section>
    <section id="admin" class="dashboard"></section>
    <section id="contact" class="contact"><h2>Contact</h2><input placeholder="Email" /><button>Send</button></section>
  </main>`;

renderAdmin(document.querySelector('.dashboard'));
document.querySelector('#demo').addEventListener('click', () => alert('Demo request captured.'));
""", encoding="utf-8")
    (frontend / "src" / "admin.js").write_text("""export function renderAdmin(root) {
  root.innerHTML = `
    <h2>Admin Dashboard</h2>
    <div class="admin-grid">
      <div><span>Users</span><strong>342</strong></div>
      <div><span>Open tasks</span><strong>18</strong></div>
      <div><span>Automations</span><strong>7 active</strong></div>
    </div>
  `;
}
""", encoding="utf-8")
    (frontend / "src" / "styles.css").write_text("""*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:#071013;color:#edf7f6}.shell{max-width:1180px;margin:auto;padding:24px}.topbar{display:flex;justify-content:space-between;align-items:center;padding:14px 0}.topbar a{color:#b8d8d8;margin-left:18px;text-decoration:none}.hero{display:grid;grid-template-columns:1.5fr .8fr;gap:28px;min-height:62vh;align-items:center}.eyebrow{color:#7ee7c8;text-transform:uppercase;font-size:12px;letter-spacing:.12em}.hero h1{font-size:clamp(42px,7vw,84px);line-height:.95;margin:0 0 18px}.lead{font-size:20px;color:#b8caca;max-width:720px}button{background:#7ee7c8;color:#06100e;border:0;border-radius:6px;padding:12px 18px;font-weight:800}.panel,.grid article,.dashboard,.contact{background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.14);border-radius:8px;padding:22px;backdrop-filter:blur(18px)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.admin-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.admin-grid div{background:#0d1c20;padding:18px;border-radius:8px}.admin-grid span{display:block;color:#9fb6b6}.admin-grid strong{font-size:28px}.contact{margin-top:18px;display:flex;gap:10px;align-items:center}.contact input{flex:1;padding:12px;border-radius:6px;border:1px solid #284348;background:#0d1c20;color:white}@media(max-width:760px){.hero,.grid,.admin-grid{grid-template-columns:1fr}.topbar{align-items:flex-start;gap:12px;flex-direction:column}}""", encoding="utf-8")

    (backend / "requirements.txt").write_text("fastapi\nuvicorn[standard]\npython-jose[cryptography]\npasslib[bcrypt]\npydantic\n", encoding="utf-8")
    (backend / "Dockerfile").write_text("""FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
""", encoding="utf-8")
    (backend / "schema.sql").write_text("""CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, email TEXT UNIQUE, password_hash TEXT, role TEXT DEFAULT 'user');
CREATE TABLE IF NOT EXISTS leads(id INTEGER PRIMARY KEY, email TEXT, source TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS automations(id INTEGER PRIMARY KEY, name TEXT, status TEXT, config_json TEXT);
""", encoding="utf-8")
    (backend / "app" / "__init__.py").write_text("", encoding="utf-8")
    (backend / "app" / "main.py").write_text(f"""from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title={brand!r}, version="1.0.0")

class Lead(BaseModel):
    email: str
    source: str = "website"

@app.get("/health")
def health():
    return {{"status": "ok"}}

@app.post("/api/leads")
def create_lead(lead: Lead):
    return {{"saved": True, "lead": lead}}

@app.get("/api/admin/metrics")
def metrics():
    return {{"users": 342, "open_tasks": 18, "automations": 7}}
""", encoding="utf-8")

    try:
        subprocess.Popen(["open", str(project_dir)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        pass
    msg = f"Production fullstack website scaffold '{proj_name}' is ready: {project_dir}"
    if speak:
        speak(msg)
    return msg


def _extract_json_object(text: str) -> dict:
    raw = _strip_fences(text)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not match:
            raise
        return json.loads(match.group(0))


SITE_DESIGN_BRIEF = """You are a world-class product designer and senior front-end engineer — the level of Lovable, Vercel, Linear, and Stripe. You build websites that make people say "wow" on the first screen.

Build a COMPLETE, production-quality, single-file website for this request:
{description}

NON-NEGOTIABLE QUALITY BAR:
- Output a SINGLE self-contained `index.html`. Everything inline (CSS in <style>, JS in <script>). It must open perfectly by just double-clicking the file.
- Use Tailwind via CDN: <script src="https://cdn.tailwindcss.com"></script>. You may extend the Tailwind config inline for custom colors/fonts.
- Use a beautiful Google Font (e.g. Inter, Sora, Space Grotesk, Manrope) via <link>.
- Use Lucide icons via CDN (https://unpkg.com/lucide@latest) and call lucide.createIcons() — NEVER use raw emoji as icons.
- Design language: modern, premium, lots of whitespace, strong typographic hierarchy, tasteful gradients, soft shadows, rounded corners, subtle glassmorphism, and a cohesive color palette that fits the brand/topic.
- Add polished micro-interactions: hover states, smooth transitions, scroll-reveal animations (IntersectionObserver), and a sticky header that adapts on scroll.
- Fully responsive: flawless on mobile, tablet, and desktop. Include a working mobile menu.
- Real, specific, believable copy in the SAME LANGUAGE as the user's request. NO lorem ipsum, no "[placeholder]", no "your text here".
- Rich structure: sticky nav, a stunning hero with a clear CTA, 3-6 meaningful sections (features/benefits, social proof/testimonials, pricing or gallery or stats as fits the topic, FAQ, strong footer). Make it feel like a real launched product.
- Include at least one piece of real interactivity in JS (e.g. working FAQ accordion, tabs, theme toggle, form validation, animated counters, or filterable cards).
- Accessible: semantic HTML, alt text, aria labels, good color contrast, keyboard-focusable controls.
- For images use https://picsum.photos or gradient/SVG placeholders that actually look good — never broken image links.

OUTPUT RULES:
- Output ONLY the raw HTML document, starting with <!doctype html>. 
- NO markdown, NO code fences, NO commentary before or after.
"""


def _generate_site_html(description: str, log=None) -> str:
    """Generate a polished, self-contained index.html for the request."""
    model = _get_model(MODEL_DESIGN)
    prompt = SITE_DESIGN_BRIEF.format(description=description)
    response = model.generate_content(
        prompt,
        generation_config={"temperature": 0.85, "max_output_tokens": 16384},
    )
    html = _strip_fences(response.text or "")
    low = html.lower()
    if "<!doctype" not in low and "<html" not in low:
        idx = low.find("<!doctype")
        if idx == -1:
            idx = low.find("<html")
        if idx != -1:
            html = html[idx:]
    if "<html" not in html.lower():
        raise ValueError("Model did not return valid HTML")
    return html.strip()


def _build_static_site(
    description: str,
    project_name: str,
    speak=None,
    player=None,
) -> str:
    def log(msg: str):
        print(f"[DevAgent] {msg}")
        if player:
            player.write_log(f"[DevAgent] {msg}")

    proj_name = _safe_project_name(project_name, "jarvis_site")
    project_dir = PROJECTS_DIR / proj_name
    project_dir.mkdir(parents=True, exist_ok=True)

    try:
        log("Designing a premium website...")
        html = _generate_site_html(description, log=log)

        index_path = project_dir / "index.html"
        index_path.write_text(html.strip() + "\n", encoding="utf-8")
        log(f"Written index.html ({len(html)} chars)")

        readme = (
            f"# {proj_name}\n\n"
            f"Generated by JARVIS — a premium, self-contained website.\n\n"
            f"Request: {description}\n\n"
            "Open `index.html` in any browser to view it. Everything is inline (no build step).\n"
        )
        (project_dir / "README.md").write_text(readme, encoding="utf-8")

        try:
            subprocess.Popen(["open", str(index_path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except Exception:
            pass

        msg = f"Готово — сайт '{proj_name}' собран и открыт: {index_path}"
        if speak:
            speak(msg)
        return msg
    except Exception as e:
        if _is_rate_limit(e):
            msg = "Лимит запросов словил, бро. Дай пару секунд и повтори."
            if speak:
                speak(msg)
            return msg
        return f"Site generation failed: {e}"


def _is_rate_limit(error: Exception) -> bool:
    msg = str(error).lower()
    return "429" in msg or "quota" in msg or "resource_exhausted" in msg


def _parse_traceback(output: str, project_files: list[str]) -> tuple[str | None, int | None]:

    pattern = re.compile(r'File ["\']([^"\']+\.py)["\'],\s+line\s+(\d+)', re.IGNORECASE)
    matches = pattern.findall(output)

    for raw_path, line_str in reversed(matches):
        raw_name = Path(raw_path).name
        for pf in project_files:
            if Path(pf).name == raw_name or pf == raw_path or raw_path.endswith(pf):
                return pf, int(line_str)

    return None, None


def _classify_error(output: str) -> str:

    low = output.lower()

    if any(x in low for x in ("no module named", "modulenotfounderror", "importerror")):
        return "dependency_error"

    if "syntaxerror" in low or "invalid syntax" in low:
        return "syntax_error"
    
    if "cannot import" in low or "importerror" in low:
        return "import_error"

    if any(x in low for x in (
        "traceback", "exception", "error:", "nameerror", "typeerror",
        "attributeerror", "valueerror", "keyerror", "indexerror",
        "zerodivisionerror", "filenotfounderror", "permissionerror",
    )):
        return "runtime_error"

    return "none"


def _has_error(output: str, run_command: str) -> bool:
    
    low = output.lower()

    if "timed out" in low:
        return False

    if not output.strip():
        return False

    error_type = _classify_error(output)
    return error_type != "none"

class RateLimitError(Exception):
    pass


def _plan_project(description: str, language: str) -> dict:
    model = _get_model(MODEL_PLANNER)

    prompt = f"""You are a senior software architect. Create a minimal, complete file plan for this project.

Language: {language}
Description: {description}

Return ONLY valid JSON — no markdown, no explanation:
{{
  "project_name": "snake_case_name",
  "entry_point": "main.py",
  "files": [
    {{
      "path": "main.py",
      "description": "Entry point — what it does and which modules it imports",
      "imports": ["utils.helpers", "core.engine"]
    }},
    {{
      "path": "utils/helpers.py",
      "description": "Helper utilities — what functions it exposes",
      "imports": []
    }}
  ],
  "run_command": "python main.py",
  "dependencies": ["requests"]
}}

Critical rules:
1. List files in DEPENDENCY ORDER — files with no imports come first, entry point comes last.
2. The "imports" field must list every other project module this file imports (dot-notation, e.g. "utils.helpers").
3. Keep it minimal — only files truly needed.
4. Entry point must be in the files list.
5. Use relative paths only (e.g. "utils/helpers.py", not absolute paths).
6. Standard library modules (os, sys, json, etc.) do NOT go in "dependencies".

JSON:"""

    try:
        response = model.generate_content(prompt)
        raw = _strip_fences(response.text)
        return json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Planner returned invalid JSON: {e}\nRaw: {response.text[:300]}")
    except Exception as e:
        if _is_rate_limit(e):
            raise RateLimitError(str(e))
        raise

def _write_file(
    file_info: dict,
    project_description: str,
    all_files: list[dict],
    language: str,
    project_dir: Path,
    already_written: dict[str, str],
) -> str:
    model = _get_model(MODEL_WRITER)

    file_path = file_info["path"]
    file_desc = file_info.get("description", "")
    file_imports = file_info.get("imports", [])

    file_list = "\n".join(
        f"  [{i+1}] {f['path']}: {f.get('description', '')}"
        for i, f in enumerate(all_files)
    )

    dependency_context = ""
    for dep_dotted in file_imports:
        dep_path = dep_dotted.replace(".", "/") + ".py"
        if dep_path in already_written:
            code_snippet = already_written[dep_path][:2000]
            dependency_context += f"\n\n--- {dep_path} (you must import from this) ---\n{code_snippet}"

    lang_rules = ""
    if language.lower() == "python":
        lang_rules = """
Python-specific rules:
- Use type hints for all function signatures.
- Add docstrings for all public functions and classes.
- Use if __name__ == "__main__": guard in the entry point.
- For relative imports within the project, use: from utils.helpers import foo  (match the project structure exactly).
- Do NOT use implicit relative imports (from . import ...) unless it's a proper package with __init__.py.
- If this is a package subdirectory, create __init__.py files where needed."""
    elif language.lower() in ("javascript", "typescript", "js", "ts"):
        lang_rules = """
JS/TS-specific rules:
- Use ES modules (import/export), not CommonJS (require).
- Add JSDoc comments for all exported functions.
- Handle promise rejections with try/catch in async functions."""

    prompt = f"""You are a senior {language} developer writing production-quality code for a real project.

Project goal: {project_description}

Complete project file structure (in dependency order):
{file_list}

{f"Dependencies this file must import from other project files:{dependency_context}" if dependency_context else ""}

Your task: Write the complete, working code for: {file_path}
Purpose of this file: {file_desc}
{f"This file imports from: {', '.join(file_imports)}" if file_imports else "This file has no project-internal imports."}

{lang_rules}

General rules:
- Output ONLY raw code. Absolutely no explanation, no markdown, no triple backticks.
- Write COMPLETE, RUNNABLE code — no placeholders, no "# TODO", no "pass" stubs.
- Every import must either be from the standard library, listed dependencies, or the project files shown above.
- Match import paths EXACTLY to the file paths in the project structure (e.g. if file is "utils/helpers.py", import as "from utils.helpers import ...").
- Use proper error handling (try/except) where I/O or network calls are made.
- The code must work correctly when the project entry point is run from the project root directory.

Code for {file_path}:"""

    try:
        response = model.generate_content(prompt)
        code = _strip_fences(response.text)

        full_path = project_dir / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(code, encoding="utf-8")

        print(f"[DevAgent] ✅ Written: {file_path} ({len(code)} chars)")
        return code

    except Exception as e:
        if _is_rate_limit(e):
            raise RateLimitError(str(e))
        raise

def _install_dependencies(dependencies: list[str], project_dir: Path) -> str:
    if not dependencies:
        return "No external dependencies."

    to_install = []
    for dep in dependencies:
        pkg_name = re.split(r"[>=<!]", dep)[0].strip()
        result = subprocess.run(
            [sys.executable, "-m", "pip", "show", pkg_name],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            to_install.append(dep)
        else:
            print(f"[DevAgent] ✓ Already installed: {pkg_name}")

    if not to_install:
        return f"All dependencies already installed: {', '.join(dependencies)}"

    print(f"[DevAgent] 📦 Installing: {to_install}")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install"] + to_install,
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
            timeout=120, cwd=str(project_dir)
        )
        if result.returncode == 0:
            return f"Installed: {', '.join(to_install)}"
        return f"Install warning (non-fatal): {result.stderr[:200]}"
    except subprocess.TimeoutExpired:
        return "Dependency install timed out (non-fatal)."
    except Exception as e:
        return f"Install error (non-fatal): {e}"

def _open_vscode(project_dir: Path) -> bool:
    vscode_candidates = [
        "code",
        rf"C:\Users\{Path.home().name}\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd",
        r"C:\Program Files\Microsoft VS Code\bin\code.cmd",
    ]
    for cmd in vscode_candidates:
        try:
            subprocess.Popen(
                [cmd, str(project_dir)],
                shell=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL
            )
            time.sleep(1.5)
            print(f"[DevAgent] 💻 VSCode opened: {project_dir}")
            return True
        except Exception:
            continue
    return False

def _run_project(run_command: str, project_dir: Path, timeout: int = 30) -> str:
    print(f"[DevAgent] 🚀 Running: {run_command}")
    try:
        parts = run_command.split()
        if parts[0].lower() == "python":
            parts[0] = sys.executable

        result = subprocess.run(
            parts,
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
            timeout=timeout,
            cwd=str(project_dir)
        )

        stdout = result.stdout.strip()
        stderr = result.stderr.strip()

        combined_parts = []
        if stdout:
            combined_parts.append(f"STDOUT:\n{stdout}")
        if stderr:
            combined_parts.append(f"STDERR:\n{stderr}")

        return "\n\n".join(combined_parts) if combined_parts else "Ran with no output."

    except subprocess.TimeoutExpired:
        return f"Timed out after {timeout}s — long-running app (server/GUI) is likely working."
    except FileNotFoundError as e:
        return f"Command not found: {e}"
    except Exception as e:
        return f"Run error: {e}"

def _try_auto_install(error_output: str, project_dir: Path) -> bool:
    """ModuleNotFoundError varsa eksik paketi otomatik kurmaya çalışır."""
    pattern = re.compile(
        r"No module named ['\"]([a-zA-Z0-9_\-\.]+)['\"]", re.IGNORECASE
    )
    match = pattern.search(error_output)
    if not match:
        return False

    pkg = match.group(1).replace("_", "-").split(".")[0]
    print(f"[DevAgent] 🔧 Auto-installing missing package: {pkg}")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", pkg],
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
            timeout=60, cwd=str(project_dir)
        )
        return result.returncode == 0
    except Exception:
        return False

def _fix_files(
    error_output: str,
    project_description: str,
    all_files: list[dict],
    file_codes: dict[str, str],
    language: str,
    project_dir: Path,
    entry_point: str,
) -> dict[str, str]:

    model = _get_model(MODEL_PLANNER)

    error_file, error_line = _parse_traceback(error_output, list(file_codes.keys()))
    error_type = _classify_error(error_output)

    files_to_fix: list[str] = []

    if error_file:
        files_to_fix.append(error_file)
        if error_type == "import_error":
            for fi in all_files:
                if error_file.replace("/", ".").replace(".py", "") in fi.get("imports", []):
                    p = fi["path"]
                    if p not in files_to_fix:
                        files_to_fix.append(p)
    else:
        files_to_fix.append(entry_point)

    updated_codes: dict[str, str] = {}

    for fix_path in files_to_fix:
        current_code = file_codes.get(fix_path, "")

        other_ctx = ""
        for fp, code in file_codes.items():
            if fp != fix_path and code:
                snippet = code[:1500] + ("..." if len(code) > 1500 else "")
                other_ctx += f"\n--- {fp} ---\n{snippet}\n"

        line_hint = f"\nError appears to be near line {error_line} in this file." if (
            error_line and fix_path == error_file
        ) else ""

        prompt = f"""You are an expert {language} debugger. Fix the broken file below.

Project goal: {project_description}

All project files:
{chr(10).join(f"  - {f['path']}: {f.get('description', '')}" for f in all_files)}

Other files for context (read-only — fix only the target file):
{other_ctx[:3500]}

File to fix: {fix_path}{line_hint}
Error type: {error_type}

Error output:
{error_output[:2500]}

Current (broken) code:
{current_code}

Rules:
- Output ONLY the complete fixed code. No explanation, no markdown, no backticks.
- Fix ALL errors visible in the error output.
- Keep all existing correct logic — do not remove working features.
- Ensure import paths match the actual project file structure exactly.
- Do NOT introduce new bugs or remove error handling.

Fixed code for {fix_path}:"""

        try:
            response = model.generate_content(prompt)
            fixed = _strip_fences(response.text)

            full_path = project_dir / fix_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(fixed, encoding="utf-8")

            updated_codes[fix_path] = fixed
            print(f"[DevAgent] 🔧 Fixed: {fix_path}")

        except Exception as e:
            if _is_rate_limit(e):
                raise RateLimitError(str(e))
            print(f"[DevAgent] ⚠️ Could not fix {fix_path}: {e}")

    return updated_codes

def _build_project(
    description: str,
    language: str,
    project_name: str,
    timeout: int,
    speak=None,
    player=None,
) -> str:

    def log(msg: str):
        print(f"[DevAgent] {msg}")
        if player:
            player.write_log(f"[DevAgent] {msg}")

    log("Planning project structure...")
    try:
        plan = _plan_project(description, language)
    except RateLimitError:
        msg = "Rate limit reached, sir. Please try again in a moment."
        if speak: speak(msg)
        return msg
    except ValueError as e:
        msg = f"Planning failed: {e}"
        if speak: speak(msg)
        return msg

    proj_name    = project_name or plan.get("project_name", "jarvis_project")
    proj_name    = re.sub(r"[^\w\-]", "_", proj_name)
    project_dir  = PROJECTS_DIR / proj_name
    project_dir.mkdir(parents=True, exist_ok=True)

    files        = plan.get("files", [])
    entry_point  = plan.get("entry_point", "main.py")
    run_command  = plan.get("run_command", f"python {entry_point}")
    dependencies = plan.get("dependencies", [])

    log(f"Project: {proj_name} | Files: {len(files)} | Entry: {entry_point}")

    def _dep_sort_key(fi: dict) -> int:
        return len(fi.get("imports", []))

    sorted_files = sorted(files, key=_dep_sort_key)

    file_codes: dict[str, str] = {}

    for file_info in sorted_files:
        file_path = file_info.get("path", "")
        if not file_path:
            continue

        log(f"Writing {file_path}...")
        for attempt in range(2):
            try:
                code = _write_file(
                    file_info=file_info,
                    project_description=description,
                    all_files=files,
                    language=language,
                    project_dir=project_dir,
                    already_written=file_codes,
                )
                file_codes[file_path] = code
                time.sleep(0.4)
                break
            except RateLimitError:
                if attempt == 0:
                    log("Rate limit — waiting 20s...")
                    time.sleep(20)
                else:
                    log(f"Rate limit retry failed for {file_path}, skipping.")
            except Exception as e:
                log(f"Failed to write {file_path}: {e}")
                break

    if not file_codes:
        msg = "I could not write any project files, sir."
        if speak: speak(msg)
        return msg

    if dependencies:
        install_result = _install_dependencies(dependencies, project_dir)
        log(install_result)

    _open_vscode(project_dir)

    last_output   = ""
    auto_installs = 0  

    for attempt in range(1, MAX_FIX_ATTEMPTS + 1):
        log(f"Running project (attempt {attempt}/{MAX_FIX_ATTEMPTS})...")
        last_output = _run_project(run_command, project_dir, timeout)
        log(f"Output preview: {last_output[:150]}")

        if not _has_error(last_output, run_command):
            msg = (
                f"Project '{proj_name}' is working, sir. "
                f"Built in {attempt} attempt{'s' if attempt > 1 else ''}. "
                f"Saved to: {project_dir}"
            )
            if speak: speak(msg)
            return f"{msg}\n\nOutput:\n{last_output}"

        if attempt == MAX_FIX_ATTEMPTS:
            break

        error_type = _classify_error(last_output)
        if error_type == "dependency_error" and auto_installs < 3:
            installed = _try_auto_install(last_output, project_dir)
            if installed:
                auto_installs += 1
                log("Missing dependency installed, retrying...")
                time.sleep(1)
                continue

        log(f"Fixing errors (type: {error_type})...")
        try:
            updated = _fix_files(
                error_output=last_output,
                project_description=description,
                all_files=files,
                file_codes=file_codes,
                language=language,
                project_dir=project_dir,
                entry_point=entry_point,
            )
            file_codes.update(updated)
            time.sleep(1)
        except RateLimitError:
            msg = "Rate limit reached during fix. Project saved, check it manually in VSCode."
            if speak: speak(msg)
            return msg
        except Exception as e:
            log(f"Fix step failed: {e}")

    msg = (
        f"I couldn't fully fix '{proj_name}' after {MAX_FIX_ATTEMPTS} attempts, sir. "
        f"Project is saved at {project_dir} — open it in VSCode and check manually."
    )
    if speak: speak(msg)
    return f"{msg}\n\nLast error:\n{last_output[:600]}"


def dev_agent(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
    speak=None,
) -> str:
    p            = parameters or {}
    description  = p.get("description", "").strip()
    language     = p.get("language", "python").strip()
    project_name = p.get("project_name", "").strip()
    project_type = p.get("project_type", "").strip()
    timeout      = int(p.get("timeout", 30))

    if not description:
        return "Please describe the project you want me to build, sir."

    if _looks_like_fullstack_site(description, language, project_type):
        return _build_fullstack_website(
            description=description,
            project_name=project_name,
            speak=speak,
            player=player,
        )

    if _looks_like_static_site(description, language, project_type):
        return _build_static_site(
            description=description,
            project_name=project_name,
            speak=speak,
            player=player,
        )

    return _build_project(
        description  = description,
        language     = language,
        project_name = project_name,
        timeout      = timeout,
        speak        = speak,
        player       = player,
    )
